### ISSUE TITLE
申请openXLab 的docker预装一下 glibc-2.29

### ISSUE THREAD

**Issue by szhowardhuang** [InternLM/tutorial#219]
在部署应用到openXLab GPU 平台环境时发现，缺省的docker缺乏glibc 2.29.
由于新版transformers的tokenizers需要2.29版本的GLIBC，所以申请预安装。

脚本如下：

`wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz`
`tar -zxvf glibc-2.29.tar.gz`
`mkdir glibc-2.29/build`
`cd glibc-2.29/build`
`../configure --prefix=/opt/glibc`
`make `
`make install`

**Comment by keyhsw** [comment]
![img_v3_026v_dc9335e5-e77d-4b6e-aeb8-b621cbbea5bg](https://github.com/InternLM/tutorial/assets/30455795/6dbd7d52-cda9-46a4-8169-3622af0ba4aa)
你好，目前OpenXLab平台已安装glibc 2.31版本，您再试试看~

**Comment by szhowardhuang** [comment]
it is ok.  issue fixed.
