### ISSUE TITLE
lmdeploy 命令 not found ,QA里的方法也试过了

### ISSUE THREAD

**Issue by aq666888** [InternLM/tutorial#463]
![36716d58b3eb8a2f245b06a37e3f79e](https://github.com/InternLM/tutorial/assets/51784054/1a7e51d3-0efa-4d27-a47f-2bc8a5275e14)
![36716d58b3eb8a2f245b06a37e3f79e](https://github.com/InternLM/tutorial/assets/51784054/159baa11-458a-47eb-ae7b-866f1b6570b8)
![36716d58b3eb8a2f245b06a37e3f79e](https://github.com/InternLM/tutorial/assets/51784054/cf1455ac-d6c2-4063-af5e-09e17c8f4f48)

**Comment by aq666888** [comment]
![15e7163b2b5e66e309e835754ecca72](https://github.com/InternLM/tutorial/assets/51784054/8a53c69f-290e-423c-86cb-e78234ef64cf)
![737b36cd2409c07fb8fb84592ec82f5](https://github.com/InternLM/tutorial/assets/51784054/dfbac756-8484-4bd5-9b42-34707d3b2b5c)

**Comment by hmzakord0692** [comment]
Kordm💯🦅

**Comment by hmzakord0692** [comment]
1.

**Comment by hmzakord0692** [comment]
### KURD`
