### ISSUE TITLE
“XTuner多模态训练与测试”训练模型指令执行报错TypeError: 'NoneType object is not subscriptable in xxxx

### ISSUE THREAD

**Issue by nami404** [InternLM/tutorial#725]
按照所提供教程执行的，到如图所示命令出现报错无法解决，求助🆘
![image](https://github.com/InternLM/Tutorial/assets/48767563/2bde4f4a-735b-464a-bb41-2f88ee74a991)
![image](https://github.com/InternLM/Tutorial/assets/48767563/282438ac-3c39-494b-897b-75667f14990f)

**Comment by qew21** [comment]
![image](https://github.com/InternLM/Tutorial/assets/25722332/71972235-d65e-4f46-b652-7d37a83663e0)

**Comment by nami404** [comment]
应该是transformers的包版本的问题，从4.41.1，改为4.40.0应该就OK了
![225446](https://github.com/InternLM/Tutorial/assets/48767563/578df71d-94b5-4ac7-abe1-82d00d84a965)

**Comment by 970602** [comment]
> 应该是transformers的包版本的问题，从4.41.1，改为4.40.0应该就OK了 ![225446](https://private-user-images.githubusercontent.com/48767563/335246891-578df71d-94b5-4ac7-abe1-82d00d84a965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjYzMzIsIm5iZiI6MTcxNzQ2NjAzMiwicGF0aCI6Ii80ODc2NzU2My8zMzUyNDY4OTEtNTc4ZGY3MWQtOTRiNS00YWM3LWFiZTEtODJkMDBkODRhOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAxNTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NjJjMTAwOGZiODU3ZDIzZmFlNWVlY2EwNzYyNjljNTJiODZkMjhiMGYxNjgwYWY0ZDc2ZWVhY2U3ZmNlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xE3AEmA9UTfGOP1CFRk7ptwNFwNFuWYQariJUnGtUgA)
我想知道，你是怎么做出判断的，要用那个版本的包，我感觉自己完全不会判断。
