### ISSUE TITLE
SSH连接问题

### ISSUE THREAD

**Issue by songqiang321** [InternLM/tutorial#78]
![mmexport1704337847650](https://github.com/InternLM/tutorial/assets/87302269/abaea709-91c4-4c7b-8f26-1f5eac9d5e37)

您好，我按照internstudio教程远程连接，最后一步显示端口被禁用，请问应该如何解决呢？

**Comment by jujimeizuo** [comment]
> ![mmexport1704337847650](https://private-user-images.githubusercontent.com/87302269/294076436-abaea709-91c4-4c7b-8f26-1f5eac9d5e37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDMwNTIsIm5iZiI6MTcwNDM0Mjc1MiwicGF0aCI6Ii84NzMwMjI2OS8yOTQwNzY0MzYtYWJhZWE3MDktOTFjNC00YzdiLThmMjYtMWY1ZWFjOWQ1ZTM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA0MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMDU5YjZiNjgyMjJkMDAxMGI5NTg4NjdhZWViZWI0MWVmNWU5M2MzMjRiMjM1NjRiMDNiZmQ5OTUwNDExODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-v2jEo-q278De5a3kMSiOTMOV9Piy99GNF8oXLvZlqc)
> 
> 您好，我按照internstudio教程远程连接，最后一步显示端口被禁用，请问应该如何解决呢？

1. 输入 ssh 连接的命令，在 InternStudio 里面复制即可
2. 然后在 SSH 列表里出现开发机的标识，点击连接即可

如果连接不了，查看 

- ssh-key 有没有配置好
- 端口有没有被占用
- 开机重启等等

<img width="683" alt="image" src="https://github.com/InternLM/tutorial/assets/61532079/c824db90-35cd-4a3d-b2b5-2801c24b7438">

**Comment by ironartisan** [comment]
SSH连接问题解决方法汇总：
1. 若是第一次连接，连接不成功，请检查：
    - ssh key位置是否有改动，不是放在默认位置下，导致读取不了
    - 确认配置的是**公钥**，不是私钥
    - 端口是否被占用
2. 若不是第一次连接，关机后开机再连接，提示无法连接：
    - 删除.ssh文件夹下的known_hosts文件

**Comment by songqiang321** [comment]
谢谢大家！
