### ISSUE TITLE
第1节课笔记(11班)

### ISSUE THREAD

**Issue by wuyingxue1230** [InternLM/tutorial#86]
### Discussed in https://github.com/InternLM/tutorial/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **Shengshenlan** January  3, 2024</sup>
</div>
https://zhuanlan.zhihu.com/p/676289592

**Comment by MING-ZCH** [comment]
请在discussion下方对应班级处提交笔记~

**Comment by williamleo0730** [comment]
https://zhuanlan.zhihu.com/p/677117655?
