### ISSUE TITLE
root的password是什么

### ISSUE THREAD

**Issue by songqiang321** [InternLM/tutorial#87]
![屏幕截图 2024-01-05 204004](https://github.com/InternLM/tutorial/assets/87302269/048ca1e6-4013-49da-ad43-d24dd1b05462)
请问配置本地端口的时候，最后一步这里的password应该填什么呢？

**Comment by songqiang321** [comment]
已经配置过公钥了，本地的key存放也没有问题，SSH远程连接和配置本地端口都会要求输入密码

**Comment by songqiang321** [comment]
我发现在internstudio配置的公钥，在本地公钥和私钥文件好像必须命名成id_rsa，命名成其他名字如internstudio_id_rsa就必须要输入root密码，请问这是否是个bug呢？

**Comment by MING-ZCH** [comment]
请具体查看QA文档中第9条~
QA文档链接：https://cguue83gpz.feishu.cn/docx/Noi7d5lllo6DMGxkuXwclxXMn5f
